server {
    listen 80;
    server_name accounts.lakewatch.tech;

    resolver 127.0.0.11 valid=30s;

    # Security headers (important for Keycloak iframe login)
    add_header Content-Security-Policy "frame-src 'self' https://accounts.lakewatch.tech;" always;

    # Proxy to Keycloak container
    location / {
        proxy_pass http://keycloak:8080;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_set_header Connection "";
    }
}