services:
  postgres:
    container_name: postgres
    image: postgres:17.6
    restart: unless-stopped
    env_file: .env
    expose:
      - "5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    networks:
      default:
        ipv4_address: ${DOCKER_NETWORK_DB_IP}

  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      target: production
    restart: unless-stopped
    expose:
      - "80"
    env_file: .env
    volumes:
      - ./backend:/var/www
    depends_on:
      - postgres
    networks:
      default:
        ipv4_address: ${DOCKER_NETWORK_API_IP}

  bff:
    build:
      dockerfile: Dockerfile
      target: production
    container_name: bff
    restart: unless-stopped
    depends_on:
      - api
    env_file:
      - .env
    volumes:
      - ./bff:/var/www
    expose:
      - "80"
    networks:
      default:
        ipv4_address: ${DOCKER_NETWORK_BFF_IP}

  reverse-proxy:
    image: nginx:1.29.3
    container_name: reverse-proxy
    restart: unless-stopped
    depends_on:
      - bff
      - api
      - keycloak
    ports:
      - "80:80" 
    volumes:
      - ./nginx/config:/etc/nginx/conf.d/
      - ./nginx/log/:/var/log/nginx/
      - ./frontend/dist:/usr/share/nginx/html
    networks:
      default:
        ipv4_address: ${DOCKER_NETWORK_PROXY_IP}

  keycloak-db:
    image: postgres:17.6
    restart: unless-stopped
    container_name: keycloak-db
    env_file:
      - .keycloak.env
    volumes:
      - ./data/keycloak-db:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      default:
        ipv4_address: ${DOCKER_NETWORK_KEYCLOAKDB_IP}

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile.keycloak
    restart: unless-stopped
    container_name: keycloak
    env_file:
      - .keycloak.env
    command: 
      - start
    depends_on:
      - keycloak-db
    expose:
      - "8080"
    networks:
      default:
        ipv4_address: ${DOCKER_NETWORK_KEYCLOAK_IP}

networks:
  default:
    name: ${DOCKER_NETWORK}
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_NETWORK_SUBNET}